version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgres  
    ports:
      - "3001:80"    
  to-do-list-page-router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to-do-list-page-router
    command: sh -c "yarn && yarn start:prod"
    working_dir: /app
    depends_on:
      - postgres
      - pgadmin
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/postgres?schema=db
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
      
volumes:
  node_modules:
  postgres-data:
