import type { AppProps } from 'next/app'
import dynamic from 'next/dynamic';
import Head from 'next/head'

const App = ({ Component }: AppProps) => {
  return (
    <>
      <Head>
        <title>Simple To Do List by Alex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component />
    </>
  )
}

export default dynamic(() => Promise.resolve(App), {
  ssr: false,
});
